Reservations/Reservations/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r"reservation/", include("reservation.urls", namespace='reservation')),
    url(r'^$', view=TemplateView.as_view(template_name='index.html'), name='index'),
)

Reservations/reservation/urls.py
from django.conf.urls import url, patterns

from .views import create_view, delete_view, search_view, show_view

urlpatterns = patterns('',
    url(r'^create/$', view=create_view, name='create_query'),
    url(r'^delete/$', view=delete_view, name='delete_query'),
    url(r'^search/$', view=search_view, name='search_query'),
    url(r'^show_result/(?P<r_id>\d+)/$', view=show_view, name='show_result'),
)

Reservations/reservation/models.py
from django.db import models


class Reservation(models.Model):
    famName = models.CharField(max_length=30, blank=False, null=False)
    arrivalDate = models.DateField(blank=False, null=False)
    departureDate = models.DateField(blank=False, null=False)
    room = models.PositiveSmallIntegerField(null=False, blank=False)

    class Meta:
        unique_together = ("room", 'famName',)

    def __unicode__(self):
        return "{}, {}".format(self.famName, self.room)

Reservations/reservation/forms.py
from datetime import date

from django import forms

from .models import Reservation


class ReservationForm(forms.Form):
    famName = forms.CharField(max_length=30, label='Familly name')
    arrivalDate = forms.DateField(label='Arrival date', input_formats=['%d-%m-%Y', '%d/%m/%Y', '%d/%m/%y'],
                                  widget=forms.TextInput(attrs={'placeholder': 'ex: 10-05-2016'}))

    departureDate = forms.DateField(label='Departure date', input_formats=['%d-%m-%Y', '%d/%m/%Y', '%d/%m/%y'],
                                    widget=forms.TextInput(attrs={'placeholder': 'ex: 25-05-2016'}))
    room = forms.IntegerField(label="Room number")


class CreateReservationForm(ReservationForm):
    def __init__(self, *args, **kwargs):
        super(CreateReservationForm, self).__init__(*args, **kwargs)


    def error_msg(self):
        raise forms.ValidationError("There is a reservation in that room in that timeframe")

    def clean(self):
        """clean method gets run once for every field"""
        cleaned_data = self.cleaned_data
        date1 = cleaned_data.get('arrivalDate')
        date2 = cleaned_data.get('departureDate')
        room = cleaned_data.get('room')
        name = cleaned_data.get('famName')

        if date1 and date1 < date.today():
            raise forms.ValidationError("You can't make reservations that are in the past")

        if (date1 and date2) and date1 >= date2:
            raise forms.ValidationError("Departure date must be greater than arrival date")

        # check if name and room are unique
        r = Reservation.objects.filter(famName=name, room=room)
        # if it exists
        if r:
            raise forms.ValidationError("There can only be one reservation per room. Try "
                                        "a different room")

        # different check than the one for uniqueness
        # dont filter by name, because name might not corespond to what's in the db
        reservation = Reservation.objects.filter(room=room)

            # if reservations with room number x exist
            # check their dates to see if they overlap
            # if they overlap raise ValidationError
        if reservation:
            for r in reservation:
                if r.arrivalDate <= date1 < r.departureDate:
                    self.error_msg()
                if r.arrivalDate < date2 <= r.departureDate:
                    self.error_msg()
                if date1 < (r.arrivalDate and r.departureDate) and date2 > (r.arrivalDate and r.departureDate):
                    self.error_msg()

        return cleaned_data


class IntermediaryReservationForm(ReservationForm):
    def __init__(self, *args, **kwargs):
        super(IntermediaryReservationForm, self).__init__(*args, **kwargs)
        del self.fields['arrivalDate']
        del self.fields['departureDate']


class DeleteReservationForm(IntermediaryReservationForm):
    def __init__(self, *args, **kwargs):
        super(DeleteReservationForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = self.cleaned_data
        name = cleaned_data.get('famName')
        room = cleaned_data.get('room')

        if name and room:
            try:
                Reservation.objects.get(famName=name, room=room).delete()
            except Reservation.DoesNotExist:
                raise forms.ValidationError("There is no reservation for {} in room {}".format(name, room))

        return cleaned_data


class FindReservationForm(IntermediaryReservationForm):
    pass

Reservations/reservation/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .forms import CreateReservationForm, DeleteReservationForm, FindReservationForm
from .models import Reservation


def create_view(request):
    form = CreateReservationForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['famName']
        arr = form.cleaned_data['arrivalDate']
        dep = form.cleaned_data['departureDate']
        room = form.cleaned_data['room']
        r = Reservation(famName=name, arrivalDate=arr, departureDate=dep, room=room)
        r.save()
        return HttpResponseRedirect(reverse('index'))
    return render(request, "reservation/create_reservation.html", {'form': form})


def delete_view(request):
    form = DeleteReservationForm(request.POST or None)
    if form.is_valid():
        return HttpResponseRedirect(reverse('index'))
    return render(request, 'reservation/delete_reservation.html', {'form': form})


def search_view(request):
    """this view is responsible for finding a reservation
    by name and room"""
    form = FindReservationForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data.get('famName')
        room = form.cleaned_data.get('room')
        try:
            if name and room:
                r = Reservation.objects.get(famName=name, room=room)

            return redirect(reverse("reservation:show_result", args=[r.id]))
        except Reservation.DoesNotExist:
            return render(request, 'reservation/show_reservation.html', {})

    return render(request, 'reservation/find_reservation.html', {'form': form})


def show_view(request, r_id):
    r = Reservation.objects.get(pk=r_id)
    return render(request, 'reservation/show_reservation.html', {'r': r})

Reservations/reservation/templates/base/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'reservation/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'reservation/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'reservation/css/signin.css' %}" rel="stylesheet">
    <link href="{% static 'reservation/css/mycontainer.css' %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>



    <div class="container">

        {% block form %}{% endblock %}


        <!--<div class="container3">-->
          <!--<a class="btn btn-lg btn-primary" href="{% url 'index' %}" role="button">Back to index page</a>-->
        <!--</div>-->

        <!--<label for="inputEmail" class="sr-only">Email address</label>-->
        <!--<input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>-->
        <!--<label for="inputPassword" class="sr-only">Password</label>-->
        <!--<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>-->
        <!--<div class="checkbox">-->
          <!--<label>-->
            <!--<input type="checkbox" value="remember-me"> Remember me-->
          <!--</label>-->
        <!--</div>-->
        <!--<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>-->
    </div> <!-- /container -->


  <script src="{% static 'reservation/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'reservation/js/bootstrap.js' %}"></script>
  <script src="{% static 'reservation/js/npm.js' %}"></script>
  </body>
</html>

Reservations/reservation/templates/reservation/create_reservation.html
{% extends 'base/base.html' %}


{% block title %}New Reservation{% endblock %}


{% block form %}
    <form class="form-signin" method="POST">
        <h2 class="form-signin-heading">Make Reservation</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Create Reservation</button><br>

        <div class="container2">
            <a class="btn btn-lg btn-primary" href="{% url 'index' %}" role="button">Back to index page</a>
        </div>
    </form>


{% endblock %}

Reservations/reservation/templates/reservation/delete_reservation.html
{% extends 'base/base.html' %}

{% block title %}Delete Reservation{% endblock %}
{% block form %}
    <form class="form-signin" method="POST">
        <h2 class="form-signin-heading">Delete a reservation</h2>
        {{ form.as_p }}
        {% csrf_token %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Delete reservation</button><br>
    </form>

    <div class="container3">
      <a class="btn btn-lg btn-primary" href="{% url 'index' %}" role="button">Back to index page</a>
    </div>
{% endblock %}

Reservations/reservation/templates/reservation/find_reservation.html
{% extends 'base/base.html' %}

{% block form %}
    <form class="form-signin" method="POST">
        <h2 class="form-signin-heading">Search for reservation</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Search</button><br>
    </form>
    <div class="container3">
      <a class="btn btn-lg btn-primary" href="{% url 'index' %}" role="button">Back to index page</a>
    </div>
{% endblock %}

Reservations/reservation/templates/reservation/show_reservation.html
{% load static %}

{% if r %}
    <table class="table table-inverse">
  <thead>
    <tr>
      <th>#</th>
      <th>Familly name </th>
      <th>Arrival </th>
      <th>Departure </th>
      <th>Room </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>{{ r.famName }}</td>
      <td>{{ r.arrivalDate }}</td>
      <td>{{ r.departureDate }}</td>
      <td>{{ r.room }}</td>
    </tr>

  </tbody>
</table>

{% else %}
    <h2>Sorry, there are no reservations with that data</h2>

{% endif %}
    <div class="container2">
      <a class="btn btn-lg btn-primary" href="{% url 'index' %}" role="button">Back to index page</a>
    </div>

Reservations/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Static Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'reservation/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'reservation/css/center_h1.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'reservation/css/navbar-static-top.css' %} " rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <br>
      <br>
      <br>
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1 class="center">Welcome</h1>
        <h2 class="center">This is the Index Page</h2>
        <p>This is where the available options are described</p>
        <p>You can create a reservation</p>
        <a class="btn btn-lg btn-primary" href="{% url 'reservation:create_query' %}" role="button">Create a reservation</a><br><br>
        <p>Delete a reservation</p>
        <a class="btn btn-lg btn-primary" href="{% url 'reservation:delete_query' %}" role="button">Delete  a reservation</a><br><br>
        <p>Search a reservation</p>
        <a class="btn btn-lg btn-primary" href="{% url 'reservation:search_query' %}" role="button">Find a reservation</a><br><br>
      </div>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'reservation/js/bootstrap.min.js' %}"></script>
  </body>
</html>